@Api_HostAddress = http://localhost:5233

### Базовая инициализация

GET {{Api_HostAddress}}/api/auth/baseInitialize
Accept: application/json

### Логин

POST {{Api_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin@demo.local",
  "password": "P@ssw0rd!1"
}

> {%
    client.global.set("Api_AccessToken", response.body.accessToken);
%}

### Аэропорты

GET {{Api_HostAddress}}/api/airports
Accept: application/json
Authorization: Bearer {{Api_AccessToken}}

### Бронирование

GET {{Api_HostAddress}}/api/bookings?flightId=,bookingStatus=1,bookingDate=
Accept: application/json
Authorization: Bearer {{Api_AccessToken}}

